// <auto-generated />
using System;
using GreenFluxAssignment.Persistence.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GreenFluxAssignment.Persistence.Migrations
{
    [DbContext(typeof(GroupContext))]
    [Migration("20210412063853_CreateInitialSchema")]
    partial class CreateInitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GreenFluxAssignment.Persistence.Entities.ChargeStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ChargeStations_Id");

                    b.HasIndex("GroupId");

                    b.ToTable("ChargeStations");
                });

            modelBuilder.Entity("GreenFluxAssignment.Persistence.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Groups_Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GreenFluxAssignment.Persistence.Entities.ChargeStation", b =>
                {
                    b.HasOne("GreenFluxAssignment.Persistence.Entities.Group", null)
                        .WithMany("ChargeStations")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_ChargeStations_Groups_GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GreenFluxAssignment.Persistence.Entities.Connector", "Connectors", b1 =>
                        {
                            b1.Property<Guid>("ChargeStationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<decimal>("MaxCurrent")
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("ChargeStationId", "Id")
                                .HasName("PK_Connectors_ChargeStationId_Id");

                            b1.ToTable("Connector");

                            b1.WithOwner()
                                .HasForeignKey("ChargeStationId")
                                .HasConstraintName("FK_Connectors_ChargeStations_ChargeStationId");
                        });

                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("GreenFluxAssignment.Persistence.Entities.Group", b =>
                {
                    b.Navigation("ChargeStations");
                });
#pragma warning restore 612, 618
        }
    }
}
